= Analytics
:keywords: analytics

API Analytics can provide insight into how your APIs are being used and how they are performing. From API Manager, you can access the Analytics dashboard, create a custom dashboard, create and manage charts, and create reports. From API Manager, you can get following types of analytics:

* API viewing analytics
* API events analytics
* Charted metrics in API Manager

You can view data from a policy perspective in the Analytics dashboard, Analytics chart, or API Manager by including policy violations. This action tracks traffic rejected, or not rejected, by a policy.

NOTE: The Analytics link is visible only to users who have Environment Admin permission. Charts are visible for users with View APIs Configuration permission.

== See Also

*** link:/api-manager/v/2.x/viewing-api-analytics[Reviewing Analytics usage]
*** link:/api-manager/v/2.x/analytics-concept[Reviewing Analytics FAQ]
*** link:/api-manager/v/2.x/analytics-chart[Reviewing API Manager Analytics charts usage]
*** link:/api-manager/v/2.x/analytics-event-api[Reviewing Analytics Event API]
*** link:/api-manager/v/2.x/analytics-event-forward[Reviewing Analytics Event Forwarding]
