= Policies
:keywords: policy, custom, ootb, offline

A policy extends the functionality of an API and enforces certain capabilities such as security. A policy can control access and traffic without modification to the API implementation. Custom policies can provide other capabilities, such as encrypting and logging.

Policies applied to APIs in the latest release of API Manager are the same as those in the earlier release with a few exceptions.

Classloader isolation exists between the application, the runtime and the connectors, and policies. To fulfill the isolation requirement, policies are self-contained and packaged to include libraries needed for execution, similar to an application.

Policies are non-blocking. You can order all policies except CORS which takes precedence over all other policies.

= Policy Management and Mule 4

In Mule 4, classloader isolation exists between application, runtime, connectors and policies.

Other changes to policies are:

* All policies are non-blocking, which is described in Mule 4 documentation.
* All policies except CORS, which is executed first, can be ordered.
* Resource level policy support, which was restricted to RAML-based APIs, is extended to any HTTP API.
* You can distribute policies outside of the runtime, which simplifies upgrades.

Mule 4 introduces changes to the packaging, size and scope of a policy.

== Provided Policies and Mule 4

Notable changes to policies for governing APIs are:

* API Manager now provides two HTTP Basic Authentication policies, one based on the simplest technique for enforcing access control to web resources and the other on the LDAP configuration.
+
If you upgrade APIs from the Jul 2017 to Nov 2017, the security manager setup information is no longer required. The policy incorporates the information.
* Header propagation no longer occurs by default. You can configure header propagation for token enforcement and rate limiting policies by checking the Expose Headers checkbox.
* You can configure the rate limiting policy to share the quota among the cluster nodes (default) or not.

// Policies
*** link:/api-manager/v/2.x/policy-scope-size-concept[Reviewing Policy Packaging, Scope, and Size concepts]
*** link:/api-manager/v/2.x/basic-policy-tasks-index[Reviewing policies basic tasks]
*** link:/api-manager/v/2.x/disable-edit-remove-task[Disabling, Editing, or Removing a Policy]
*** link:/api-manager/v/2.x/re-order-policies-task[Re-ordering Policies]
*** link:/api-manager/v/2.x/using-policies[Applying a Policy]
*** link:/api-manager/v/2.x/tutorial-manage-an-api[Applying a Policy and SLA Tier]
*** link:/api-manager/v/2.x/resource-level-policies-about[Reviewing Resource Level Policies]
*** link:/api-manager/v/2.x/resource-level-policy-reference[Reviewing Resource Level Policy concepts]
*** link:/api-manager/v/2.x/prepare-raml-task[Reviewing Traits & policies concepts of RAML based APIs]

== Provided Policies
*** link:/api-manager/v/2.x/policies-ootb-landing-page[Provided Policies]

== Custom Policies
*** link:/api-manager/v/2.x/policies-custom-landing-page[Custom Policies]

== See Also

// Link to non-blocking in Mule 4

* link:/getting-started/api-lifecycle-overview[About Availability of the November Release]
* link:/api-manager/v/2.x/policy-scope-size-concept[About Policy Packaging, Scope, and Size]
