= Mule Functions
:keywords: lookup, properties, functions

The `p`, `lookup`, and `causedBy` functions are always available in Mule 4 Runtime, although they are not part of the Core component.
You'll use these basic functions often in DataWeave expressions and scripts.

== Accessing Properties (p Function)

The `p` function provides access to properties, whether these are:

* Mule property placeholders
* System properties
* Environment properties

The following example will log the value of the property `some.property`.

.Example: Property Function Usage
[source,xml, linenums]
----
<flow name="simple">
  <logger message="#[p('some.property')]"/>
</flow>
----

== Executing a Flow (lookup Function)

The `lookup` function executes a flow within your app and retrieves the
resulting payload, taking the flow's name and an input payload as parameters.

The specified flow is executed using the current attributes, variables, and
error. It only replaces the payload for the first parameter, which must be a Java
type.

== Matching Errors by Types (causedBy Function)

The `causedBy` function matches an error by its type, like an error handler
does. This is useful when matching by a super type is required but specific sub-type
logic also needed or when handling a `COMPOSITE_ROUTING` error that contains child
errors of different types.

The error to match against can be implicit, but the type is always a required parameter.

In the following example, a global error handler is set up to handle `SECURITY`
errors in a general way, while specific actions are set up for `HTTP:UNAUTHORIZED`
and `HTTP:FORBIDDEN` errors.

.Example: Error Matcher Function Usage
[source,xml, linenums]
----
<error-handler name="securityHandler">
  <on-error-continue type="SECURITY">
    <!-- general error handling for all SECURITY errors -->
    <choice>
      <when expression="#[error causedBy 'HTTP:UNAUTHORIZED']">
        <!-- specific error handling only for HTTP:UNAUTHORIZED errors -->
      </when>
      <when expression="#[causedBy('HTTP:FORBIDDEN')]">
        <!-- specific error handling only for HTTP:FORBIDDEN errors -->
      </when>
    </choice>
  </on-error-continue>
</error-handler>
----

Notice that the error parameter is used both explicitly and implicitly.

== See Also

* link:dw-functions[DataWeave Core Functions]
* link:configuring-properties[Configuring Properties]
* link:dataweave-lookup[Call External Flows with `lookup`]
