= DataWeave Functions

Mulesoft provides several kinds of functions:

* link:dw-core[Core Functions] that are always available in Mule Runtime 4, because they are in the Core module is included in Mule 4
* link:dataweave-runtime-functions[Three Mule functions] that are always available in Mule Runtime
* Functions that you import as part of a component, connector, or module such as Batch 
* link:dataweave-defining-functions[Custom functions] that you define
* link:dataweave-functions-lambda[Anonymous fucntions (lamdas)]

These functions are all described in the link:dw-functions[DataWeave Function Reference]

== Functions and Namespaces

These DataWeave functions don't require that you include a namespace when you call them:

* Core Functions
* The three Mule functions `p`, `lookup`, and `causedBy`
* Custom functions that you create

These functions require a namespace, which usually matches the component name:

* Functions in a non-Core component that you've added to a Mule app, such as Batch or Runtime
* Functions in a connector that you've added to a Mule app, such as HTTP Connector

For example, in an app using Batch you can use the following expression: `#[Batch::isSuccessfulRecord()]`. 

== See Also

* link:dataweave-lookup[Call External Flows with `lookup`]
* link:dw-functions[DataWeave Reference]
* link:dataweave-create-module[Creating Custom Modules and Mappings]