= About the Compression Module
:keywords: compression, module, zip, gzip, tar, archive, compress, extract, unzip
:toc:
:toc-title:

A file archiver is a computer program that combines a number of files together into one archive file  for easier transportation or storage and most archivers employ data compression in their archive formats to reduce the size of the final archive. But not all compression algorithms knows how to archive files, some of them only cares about single file data compression.
The Compression module aims to support the most used archiver and compression formats, providing access to their functionalities as part of a Mule application.

The goal of this module is to provide the same experience to compress and decompress files for each of the available formats without losing any of the features that the format associated algorithm provides.

To achieve this it will provide two pairs of operations, one for compressing/decompressing a single file, and another for archive/extract a bundle of files. Each of this operations can be configured with the compression or archiving strategies of choice.


= Compressing and Decompressing a Single File

== Content Compression

Given an input stream, compresses it and returns a new compressed stream of bits so it can be stored in a file system or transferred to another system.

=== Compressor Strategies

A *compressor* strategy knows how to compress a file or single entry archives.

==== GZip Compressor Strategy

When used in an operations, declares that the content should be compressed with the *gzip* format.

[source, xml, linenums]
----
<compression:gzip-compressor/>
----

==== Zip Compressor Strategy

When used in an operations, declares that the content should be compressed with the *zip* format.

[source, xml, linenums]
----
<compression:zip-compressor/>
----

=== Compress Operation

[source, xml, linenums]
----
<compression:compress>
   <compression:content>#[payload.data]</compression:content> // <1>
   <compression:compressor>
       <compression:zip-compressor/> // <2>
   </compression:compressor>
</compression:compress>
----


1) The InputStream to be compressed, defaulting to _#[payload]_.
2) Compressor strategy to be used.

==== Compression Errors

If an error occur while compressing the content a `COMPRESSION:COULD_NOT_COMPRESS` error will be thrown.







== Content Decompression

Decompresses a given single-entry compressed content which is assumed to be an archive in the specified compression format.

=== Decompressor Strategies

A *compressor* strategy knows how to decompress a file or single entry archives.

==== GZip Decompressor Strategy

When used in an operations, declares that the content should be decompressed with the *gzip* format.

[source, xml, linenums]
----
<compression:gzip-decompressor/>
----

==== Zip Decompressor Strategy

When used in an operations, declares that the content should be decompressed with the *zip* format.

[source, xml, linenums]
----
<compression:zip-decompressor/>
----

=== Decompress Operation

[source, xml, linenums]
----
<compression:decompress>
   <compression:content>#[payload]</compression:content> // <1>
   <compression:decompressor>
       <compression:gzip-decompressor/> // <2>
   </compression:decompressor>
</compression:decompress>
----


1) The InputStream to be decompressed, defaulting to _#[payload]_.
2) Decompressor strategy to be used.

==== Decompression Errors

If the given content is does not match the formaat of the configured strategy a `COMPRESSION:INVALID_ARCHIVE` error will be thrown.

If the archive passed to be decompressed has more than one entry this operation will fail with a `COMPRESSION:TOO_MANY_ENTRIES` error, because it won't be able to choose only one entry to return, for that cases the user should use the *extract* operation.






= Archiving and Extracting a Multiple Entries

== Archiving

Given an Map of `<entryName,InputStream>`, compresses all the given entries into a new archive in the configured format.

=== Archiver Strategies

An *archiver* strategy is a compressor strategy that knows how to compress multiple entries into an archive.

==== Zip Archiver Strategy

When used in an operations, declares that the content should be compressed with the *zip* format.

[source, xml, linenums]
----
<compression:zip-archiver/>
----

=== Archive Operation

Receives a map declaring the entries to be compressed and their values, then, each entry passed to this operation will be placed inside the compressed archive with the name provided by the user.

[source, xml, linenums]
----
<compression:archive>
   <compression:entries> // <1>
    #[
       {
         summary.pdf: vars.summary,
         'details/result_001.pdf': vars.file1
         'details/result_002.pdf': vars.file2
       }
     ]
   </compression:entries>
   <compression:archiver>
       <compression:zip-archiver/> // <2>
   </compression:archiver>
</compression:archive>
----

1) A DataWeave script defining each name of the entry to be compressed as key, and the content of that entry as value.
2) The archiver strategy to be used.

The resulting archive will contain *three entries* one named "summary.pdf" at root level and another two called "result_001.pdf", "result_002.pdf" inside a directory called "details":

[source]
----
+- content.zip
|  \- summary.pdf
|  \+ details
   |  \- result_001.pdf
   |  \- result_002.pdf

----

As you can see in the example, *the slash "/" in the name of an entry indicates directory separation*, so all names will be introspected to create dirs inside the archive.

==== Archiving Errors

If a problem occur while compressing the content a `COMPRESSION:OULD_NOT_COMPRESS` error will be thrown.






== Extract

Decompresses a given content that represents archive in some compression format.

=== Extractor Strategies

An *extractor* strategy can decompress an archive with multiple entries that is compressed in some particular format.

==== Zip Strategy

When used in an operations, declares that the content should be extracted with the *zip* format.

[source, xml, linenums]
----
<compression:zip-archiver/>
----

=== Extract Operation

[source, xml, linenums]
----
<compression:extract>
    <compression:compressed>#[vars.archive]</compression:compressed> // <1>
    <compression:extractor>
        <compression:zip-extractor/> // <2>
    </compression:extractor>
</compression:extract>
----


1) The compressed content to be extracted, defaulting to `#[payload]`.
2) The entries of this archive will be returned as an object and each of them will be accessible by it's name. E.g. if an archive with three entries with the following structure is decompressed:

[source]
----
+- Archive
|  \- summary.pdf
|  \+ details
   |  \- result_001.pdf
   |  \- result_002.pdf
----

Accessing the entries once the content is extract would be: `payload['summary.pdf']` or `payload.details['result_001.pdf']`

==== Extractor Errors

If the given content is not in the configured format an `COMPRESSION:INVALID_ARCHIVE` error will be throw. For other errors while compressing the operation will throw a `COMPRESSION:COULD_NOT_DECOMPRESS` error.


== Common Use cases

=== Compressing a File

Read a file, compress it and save it.
[source, xml, linenums]
----
<file:read path="file.txt"/>
<compression:compress>
   <compression:compressor>
       <compression:gzip-compressor/>
   </compression:compressor>
</compression:compress>
<file:write path="file-txt.gz"/>
----


=== Decompress a Payload from a Remote Service

Calls a server that returns a zip file as result and decompress it.

[source, xml, linenums]
----
<wsc:consume config="ZipServiceConfig" operation="returnsZip"/>
<compression:decompress>
   <compression:content>
      #[payload.body.zipContent]
   </compression:content>
   <compression:decompressor>
       <compression:zip-decompressor/>
   </compression:decompressor>
</compression:decompress>
----
